name: Dev Workflows
on:
  push:
    branchs:
    - main
jobs:
  dev-job-first:
    name: dev-job-first
    runs-on: ubuntu-latest
    steps:
    - name: step 1
      run: |
          echo "step 1 start time"
          date +"%Y-%m-%d %H:%M:%S.%N"
    - name: step 2
      run: |
          echo "step 2 start time"
          date +"%Y-%m-%d %H:%M:%S.%N"
