name: Dev Workflows
on:
  push:
    branches:
    - main
jobs:
  dev-job-first:
    name: dev-job-first
    runs-on: ubuntu-latest
    steps:
    - name: Crate a dev.txt
      run: echo "dev file" > dev.txt
    - uses: actions/upload-artifact@4
      with:
        name: dev-artifact
        path: ./dev.txt
        
